# Generated by Django 2.2.5 on 2019-09-07 12:51

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'route'), (1, 'boulder'), (2, 'crossing')], default=0)),
                ('presas', jsonfield.fields.JSONField(blank=True, default=dict, help_text='List of coordinates')),
                ('seguros', jsonfield.fields.JSONField(blank=True, default=dict, help_text='List of coordinates')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.Area')),
                ('routes', models.ManyToManyField(related_name='routes_all', to='walls.Route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(help_text='Sector where the route is. If it crosses several sectors, then this is where the the route starts', on_delete=django.db.models.deletion.PROTECT, to='walls.Sector'),
        ),
    ]
