# Generated by Django 2.2.5 on 2019-09-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('rep1', models.IntegerField(blank=True, verbose_name=((0, 'Pie libre'), (1, 'Pie mano')))),
                ('rep2', models.IntegerField(blank=True, verbose_name=((0, 'A vista'), (1, 'Flash')))),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='walls.Route')),
            ],
            options={
                'ordering': ['-datetime', '-timestamp'],
            },
        ),
    ]
