# Generated by Django 2.2.5 on 2019-09-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0002_auto_20190907_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sector',
            name='routes',
        ),
        migrations.AddField(
            model_name='route',
            name='sectors_by',
            field=models.ManyToManyField(related_name='route_all', to='walls.Sector'),
        ),
        migrations.AlterField(
            model_name='repetition',
            name='rep1',
            field=models.IntegerField(blank=True, verbose_name=((0, 'Pie libre'), (1, 'Pie mano'))),
        ),
        migrations.AlterField(
            model_name='repetition',
            name='rep2',
            field=models.IntegerField(blank=True, verbose_name=((0, 'A vista'), (1, 'Flash'))),
        ),
        migrations.RemoveField(
            model_name='route',
            name='presas',
        ),
        migrations.AlterField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(help_text='Sector where the route is. If it crosses several sectors, then this is where the the route starts', on_delete=django.db.models.deletion.PROTECT, related_name='route_start_set', to='walls.Sector'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='seguros',
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='PresaCatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_rel', models.IntegerField()),
                ('y_rel', models.IntegerField()),
                ('angle', models.IntegerField()),
                ('presa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.Presa')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.Route')),
            ],
        ),
        migrations.AddField(
            model_name='presa',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.Sector'),
        ),
        migrations.AddField(
            model_name='route',
            name='presas',
            field=models.ManyToManyField(through='walls.PresaCatch', to='walls.Presa'),
        ),
        migrations.AddField(
            model_name='route',
            name='seguros',
            field=models.ManyToManyField(to='walls.Seguro'),
        ),
    ]
