# Generated by Django 2.2.5 on 2019-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0005_auto_20190907_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='rep1',
            field=models.IntegerField(blank=True, verbose_name=((0, 'Pie libre'), (1, 'Pie mano'))),
        ),
        migrations.AlterField(
            model_name='repetition',
            name='rep2',
            field=models.IntegerField(blank=True, verbose_name=((0, 'A vista'), (1, 'Flash'))),
        ),
    ]
