# Generated by Django 2.2.5 on 2019-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0008_auto_20190907_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
